# Generated by Django 4.0.5 on 2022-06-10 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postsk', '0003_catogry'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='postsk.catogry'),
            preserve_default=False,
        ),
    ]
